### ISSUE TITLE
After clicking stop button you can't click play button (it doesn't work)

### ISSUE THREAD

**Issue by wpitek** [tkowalczyk/DevTalkMobile#16]
I must go back and reselect podcast.

**Comment by tkowalczyk** [comment]
OK I will check this out, could you add info about your device and android version too, thank you

**Comment by wpitek** [comment]
Nexus 7 Android 5.1
Nexus 4 Android 5.1

**Comment by wpitek** [comment]
Nexus 7 Android 5.1
Nexus 4 Android 5.1

**Comment by tkowalczyk** [comment]
Some resources which might help to solve this issue:
Android: https://blog.xamarin.com/background-audio-streaming-with-xamarin.android/
iOS: http://developer.xamarin.com/guides/ios/application_fundamentals/backgrounding/part_3_ios_backgrounding_techniques/
https://github.com/mikebluestein/StreamWebAudio/tree/master/StreamWebAudio
https://developer.xamarin.com/samples/monotouch/StreamingAudio/

and of course:
http://developer.xamarin.com/guides/cross-platform/xamarin-forms/dependency-service/
