### ISSUE TITLE
After long tap on list element application crashed

### ISSUE THREAD

**Issue by slawciu** [tkowalczyk/DevTalkMobile#22]
Video with bug:
https://drive.google.com/open?id=0B1bbQeJzC5a0S0NtQ0Q4X2w1TXc&authuser=0

**Comment by tkowalczyk** [comment]
It looks like this is Xamarin.Forms issue in the current release (1.4.2) it should be fixed in 1.4.3.
Source: https://bugzilla.xamarin.com/show_bug.cgi?id=27974
